name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    environment: github-pages
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Debug env vars
      run: |
        echo "SUPABASE : $VITE_SUPABASE_URL"
        echo "AUTH0 : $VITE_AUTH0_DOMAIN"
    - name: Build
      env:
          VITE_AUTH0_DOMAIN: ${{ vars.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ vars.VITE_AUTH0_CLIENT_ID }}
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY }}
          VITE_AUTH0_AUDIENCE: ${{ vars.VITE_AUTH0_AUDIENCE }}
      run: |
        echo "SUPABASE : $VITE_SUPABASE_URL"
        echo "AUTH0 : $VITE_AUTH0_DOMAIN"
        npm install
        npm run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v4
